### PR TITLE
Add Autopilot

### PR DESCRIPTION
**Pull request by szhu**
Hi! Thanks for making this game -- it's so fun! I've spent way too long playing it the past few days.

I think I figured out a good strategy for the game, and implemented an autopilot so that everyone can experience what it's like to win big :D

See the README in the fork for more info: https://github.com/szhu/lunar-lander-autopilot

Demo:

<https://user-images.githubusercontent.com/1570168/224213713-fb3ae806-d568-4df3-b837-66c66634d9a6.mov>

<br>

btw, posted this on HN too! https://news.ycombinator.com/show

Note: I marked this PR as a draft because it's a little hacky -- I used global variables to expose stats to the autopilot code. I'm also not sure if you'd actually want to put a cheatbot into the game for everyone to use… maybe it can be an easter egg?

### CODE REVIEW

**Comment by ehmorris** [comment]
This is SO cool, I am going to take a close look this weekend

**Comment by ehmorris** [comment]
Merged this into a branch where I'll make some changes to data passing, CSS, and the stats

**Comment by ehmorris** [comment]
Now that I've released the daily challenge feature I'll take a closer look at this

**Comment by szhu** [comment]
Oh awesome! Let me open a PR that contains my newer changes.

**Pull request merged**
